[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
phf = { version = "0.11.1", features = ["macros"] }

[lints.clippy]
module-name-repetitions = "allow"
wildcard-imports = { level = "allow", priority = 1 }
enum-glob-use = "allow"
option-option = "allow"
